### ISSUE TITLE
Bug Report: pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects for 'growth_signals()'

### ISSUE THREAD

**Issue by odb9402** [SimFin/simfin#27]
# Bug Report

## Description

During following up the tutorial in [here](https://github.com/SimFin/simfin-tutorials/blob/master/09_Machine_Learning.ipynb), I got the error, `pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects`, in
`sf.StockHub.growth_signals(variant='daily')`.

Similar issue here: https://github.com/SimFin/simfin/issues/26

## System Details

- Python version == 3.11.5
- Simfin version == 1.0.1
- Other relevant package versions
    - pandas == 2.2.2 
- Operation System and version
   - macOS Ventura 13.4
- Computer's CPU, RAM-size, free HD space, etc.
   - 16G RAM
   - Apple M2
   - (302GB / 494.38GB) 
- Other relevant system information

## Code Example

```python3
   # Copied from the Simfin tutorial

    import simfin as sf

    # Configure simfin.
    sf.set_data_dir('~/simfin_data/')
    sf.load_api_key(path='~/simfin_api_key.txt', default_key='free')

    market = 'us'
    
    offset = pd.DateOffset(days=60)
    
    refresh_days = 0
    refresh_days_shareprices = 10
    
    hub = sf.StockHub(market=market, offset=offset,
                      refresh_days=refresh_days,
                      refresh_days_shareprices=refresh_days_shareprices)
    
    df_growth_signals = hub.growth_signals(variant='daily') # Error here
    df_fin_signals = hub.fin_signals(variant='daily')
    df_val_signals = hub.val_signals(variant='daily')
    
    dfs = [df_fin_signals, df_growth_signals, df_val_signals]
    df_signals = pd.concat(dfs, axis=1)

```

## Result / Error

```
(base) dongpinoh@Dongpinui-MacBookPro pinsfund % python test.py
/Users/dongpinoh/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
Dataset "us-income-ttm" on disk (0 days old).
- Downloading ... 100.0%
- Extracting zip-file ... Done!
/Users/dongpinoh/anaconda3/lib/python3.11/site-packages/simfin/load.py:154: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv(path, sep=';', header=0,
- Loading from disk ... Done!
Dataset "us-income-quarterly" on disk (0 days old).
- Downloading ... 100.0%
- Extracting zip-file ... Done!
/Users/dongpinoh/anaconda3/lib/python3.11/site-packages/simfin/load.py:154: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv(path, sep=';', header=0,
- Loading from disk ... Done!
Dataset "us-balance-ttm" on disk (0 days old).
- Downloading ... 100.0%
- Extracting zip-file ... Done!
/Users/dongpinoh/anaconda3/lib/python3.11/site-packages/simfin/load.py:154: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv(path, sep=';', header=0,
- Loading from disk ... Done!
Dataset "us-balance-quarterly" on disk (0 days old).
- Downloading ... 100.0%
- Extracting zip-file ... Done!
/Users/dongpinoh/anaconda3/lib/python3.11/site-packages/simfin/load.py:154: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv(path, sep=';', header=0,
- Loading from disk ... Done!
Dataset "us-cashflow-ttm" on disk (0 days old).
- Downloading ... 100.0%
- Extracting zip-file ... Done!
/Users/dongpinoh/anaconda3/lib/python3.11/site-packages/simfin/load.py:154: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv(path, sep=';', header=0,
- Loading from disk ... Done!
Dataset "us-cashflow-quarterly" on disk (0 days old).
- Downloading ... 100.0%
- Extracting zip-file ... Done!
/Users/dongpinoh/anaconda3/lib/python3.11/site-packages/simfin/load.py:154: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv(path, sep=';', header=0,
- Loading from disk ... Done!
Dataset "us-shareprices-daily" on disk (0 days old).
/Users/dongpinoh/anaconda3/lib/python3.11/site-packages/simfin/load.py:154: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv(path, sep=';', header=0,
- Loading from disk ... Done!
Cache-file 'growth_signals-2a38bb7d.pickle' not on disk.
- Running function growth_signals() ... Traceback (most recent call last):
  File "/Users/dongpinoh/pinsfund/test.py", line 30, in <module>
    df_growth_signals = hub.growth_signals(variant='daily')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dongpinoh/anaconda3/lib/python3.11/site-packages/simfin/hubs.py", line 582, in growth_signals
    df_result = growth_signals(df_income_ttm=df_income_ttm,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dongpinoh/anaconda3/lib/python3.11/site-packages/simfin/cache.py", line 266, in wrapper
    df_result = func(**kwargs)
                ^^^^^^^^^^^^^^
  File "/Users/dongpinoh/anaconda3/lib/python3.11/site-packages/simfin/signals.py", line 644, in growth_signals
    df_qrt = pd.concat([df_qrt1, df_qrt2, df_qrt3], axis=1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dongpinoh/anaconda3/lib/python3.11/site-packages/pandas/core/reshape/concat.py", line 395, in concat
    return op.get_result()
           ^^^^^^^^^^^^^^^
  File "/Users/dongpinoh/anaconda3/lib/python3.11/site-packages/pandas/core/reshape/concat.py", line 680, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dongpinoh/anaconda3/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3885, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects
```

**Comment by thf24** [comment]
thanks for the report. We are currently doing some large changes to the data for the next update (will be online in the next days) so this might be related. Will update you once this is fixed.

**Comment by thf24** [comment]
should work again now, sorry for the inconvenience.

**Comment by yubobao27** [comment]
This issue is still happening.

Line signals.py:793 below is trying to concatenate 3 dfs with duplicated index.

df = pd.concat([df_inc, df_bal, df_cf], axis=1)

Stack trace:
```
File ~/anaconda3/lib/python3.10/site-packages/simfin/signals.py:793, in val_signals(df_prices, df_income_ttm, df_balance_ttm, df_cashflow_ttm, fill_method, offset, func, date_index, shares_index, group_index, banks, insurance)
    790 df_cf = df_cashflow_ttm[columns]
    792 # Combine all the data. This creates a new copy that we can add columns to.
--> 793 df = pd.concat([df_inc, df_bal, df_cf], axis=1)
    795 # Calculate derived financial data such as Free Cash Flow (FCF),
    796 # and add it as new columns to the DataFrame.
    797 # This is only TTM data with 4 data-points per year, so it is
    798 # faster than calculating it for the daily data-points below.
    799 df[FCF] = free_cash_flow(df_cashflow_ttm)

File ~/anaconda3/lib/python3.10/site-packages/pandas/core/reshape/concat.py:395, in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    380     copy = False
    382 op = _Concatenator(
    383     objs,
    384     axis=axis,
   (...)
    392     sort=sort,
    393 )
--> 395 return op.get_result()

File ~/anaconda3/lib/python3.10/site-packages/pandas/core/reshape/concat.py:680, in _Concatenator.get_result(self)
    678         obj_labels = obj.axes[1 - ax]
    679         if not new_labels.equals(obj_labels):
--> 680             indexers[ax] = obj_labels.get_indexer(new_labels)
    682     mgrs_indexers.append((obj._mgr, indexers))
    684 new_data = concatenate_managers(
    685     mgrs_indexers, self.new_axes, concat_axis=self.bm_axis, copy=self.copy
    686 )

File ~/anaconda3/lib/python3.10/site-packages/pandas/core/indexes/base.py:3892, in Index.get_indexer(self, target, method, limit, tolerance)
   3889 self._check_indexing_method(method, limit, tolerance)
   3891 if not self._index_as_unique:
-> 3892     raise InvalidIndexError(self._requires_unique_msg)
   3894 if len(target) == 0:
   3895     return np.array([], dtype=np.intp)

InvalidIndexError: Reindexing only valid with uniquely valued Index objects
```
